export const AUTH = {
    LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
    LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
    SET_USER_INFO: 'AUTH_SET_USER_INFO',
    SET_AUTH_ERRORS: 'AUTH_SET_AUTH_ERRORS',
    FETCH_USER_INFO_REQUEST: 'AUTH_FETCH_USER_INFO_REQUEST'
};

export const UI = {
    SET_APP_LOADING: 'UI_SET_APP_LOADING',
    SHOW_NOTIFICATION: 'UI_SHOW_NOTIFICATION',
    HIDE_NOTIFICATION: 'UI_HIDE_NOTIFICATION'
};

export const WALLET = {
    LOAD_WALLETS_REQUEST: 'WALLET_LOAD_WALLETS_REQUEST',
    SET_WALLETS: 'WALLET_SET_WALLETS',
    LOAD_WALLET_REQUEST: 'WALLET_LOAD_WALLET_REQUEST',
    SET_WALLET: 'WALLET_SET_WALLET',
    START_POLLING: 'WALLET_START_POLLING',
    CLEAR_WALLET: 'WALLET_CLEAR_WALLET',
    SEND_COINS_REQUEST: 'WALLET_SEND_COINS_REQUEST',
    SET_SEND_MONEY_STEP: 'WALLET_SET_SEND_MONEY_STEP',
    SET_TRANSFERS: 'WALLET_SET_TRANSFERS'
};
